CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_MUSICA_2ANO;
USE BD_APLICATIVO_MUSICA_2ANO;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(14) PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    FOTO BLOB NOT NULL,
    QUANTIDADE_MUSCICAS INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	DESCRICAO VARCHAR(250) NOT NULL,
    NOME VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
    FOTO BLOB NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    LETRA BLOB NOT NULL,
	AVALIACAO INTEGER NOT NULL,
    FK_ID_ALBUM INTEGER,
    FK_ID_GENERO INTEGER,
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID),
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO(ID)
);