CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU_AREA_ATUACAO VARCHAR(200),
    USU_PROSISSAO VARCHAR(200),
    USU_AREA_FORMACAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO","CASADO","DIVORCIADO","VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL","MÉDIO","SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR (255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (USU_CODIGO)
);

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_FINAL DATE,
    ENQ_DATA_INICIAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(500) NOT NULL,
    ENQ_NOME VARCHAR(255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (ENQ_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
	FK_USU_CODIGO INTEGER,
	FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY (URE_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE,
	FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(500) NOT NULL,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (PER_CODIGO),
	FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR(500) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (RES_CODIGO),
	FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS (PER_CODIGO) ON DELETE CASCADE
);

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROSISSAO, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES 
("2025-01-15", "joaosilva", "TI", "Analista de Sistemas", "Ciência da Computação", "1995-06-20", "SOLTEIRO", "SP", "SUPERIOR", "joao.silva@email.com", "senha123", "João Silva");

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROSISSAO, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES 
("2025-02-10", "maria_edu", "Educação", "Professora", "Pedagogia", "1988-03-11", "CASADO", "RJ", "SUPERIOR", "maria.edu@email.com", "senha456", "Maria Eduarda");

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROSISSAO, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES 
("2025-03-05", "carloseng", "Engenharia", "Engenheiro Civil", "Engenharia Civil", "1990-11-02", "DIVORCIADO", "MG", "SUPERIOR", "carlos.eng@email.com", "senha789", "Carlos Andrade");

SELECT * FROM USUARIO;

INSERT INTO ENQUETE (ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES
("2025-02-20", "2025-02-01", "Pesquisa sobre uso de tecnologia no dia a dia", "Uso de Tecnologia", 1);

INSERT INTO ENQUETE (ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES
("2025-03-15", "2025-03-01", "Enquete sobre hábitos de leitura", "Hábitos de Leitura", 2);

INSERT INTO ENQUETE (ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES
("2025-04-10", "2025-03-20", "Preferências em relação a esportes", "Esportes Favoritos", 3);

SELECT * FROM ENQUETE;

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES
("2025-02-05", 1, 1);

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES
("2025-03-02", 2, 2);

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES
("2025-03-25", 3, 3);

SELECT * FROM USUARIO_RESPONDE_ENQUETE;

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES
("Você utiliza o celular quantas horas por dia?", 1);

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES
("Quantos livros você lê por ano?", 2);

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES
("Qual seu esporte favorito?", 3);

SELECT * FROM PERGUNTAS;

INSERT INTO RESPOSTAS (RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES
("Sim, diariamente", "N", 1);

INSERT INTO RESPOSTAS (RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES
("Entre 5 e 10 livros", "N", 2);

INSERT INTO RESPOSTAS (RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES
("Futebol", "N", 3);

SELECT * FROM RESPOSTAS;