CREATE DATABASE IF NOT EXISTS BD_GESTAO_ESTOQUE;
USE BD_GESTAO_ESTOQUE;

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
    DESCRICAO_PODRUTO VARCHAR (255)
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR (255)
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	CODIGO VARCHAR (13)PRIMARY KEY,
	DATA_VALIDADE DATE NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FK_ID_CATEGORIA INTEGER,
	FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FORNECEDOR_PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,FK_CONSUMIDOR_CPF VARCHAR(20),
    FK_CNPJ_FORNECEDOR VARCHAR(20),
    FK_CODIGO_PRODUTO VARCHAR (13),
    FOREIGN KEY (FK_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ) ON DELETE CASCADE,
    FOREIGN KEY (FK_CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO) ON DELETE CASCADE
);
