CREATE DATABASE IF NOT EXISTS BD_GEREN_BIBLIO_DIG;
USE BD_GEREN_BIBLIO_DIG;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR (14) PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR (13) NOT NULL
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR (14) PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR (13) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	TITULO VARCHAR (255) NOT NULL,
	CATEGORIA VARCHAR (255) NOT NULL,
	DESCRICAO VARCHAR (255),
    EDITORA VARCHAR (255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FK_AUTOR_CPF VARCHAR(14),
    FK_LEITOR_CPF VARCHAR (14),
    FOREIGN KEY (FK_AUTOR_CPF) REFERENCES AUTOR(CPF),
    FOREIGN KEY (FK_LEITOR_CPF) REFERENCES LEITOR(CPF)
);

