CREATE DATABASE IF NOT EXISTS BD_PASSAGENS_AEREAS;
USE BD_PASSAGENS_AEREAS;

CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_EMBARQUE DATE NOT NULL,
    QUANTIDADE_PESSOAS VARCHAR(850),
	VALOR INTEGER NOT NULL,
    AVALIACAO INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    PASSAPORTE VARCHAR(8) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTOS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VALOR DOUBLE NOT NULL,
    DESCRICAO VARCHAR (255),
    FK_ID_VOO INTEGER,
    FK_PASSAGEIRO_CPF VARCHAR (14),
    FOREIGN KEY (FK_ID_VOO) REFERENCES VOO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_PASSAGEIRO_CPF) REFERENCES PASSAGEIRO(CPF) ON DELETE CASCADE
);

