CREATE DATABASE IF NOT EXISTS BD_ALUGUEL_PRODUTOS;
USE BD_ALUGUEL_PRODUTOS;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QTD_DISPONIVEL INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALUGUEL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL NOT NULL,
    FK_CLIENTE_ID INTEGER NOT NULL,
	FK_PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID) ON DELETE CASCADE
);

-- DML - LINGUAGEM DE MANIPULAÇÃO
-- INSERT - INSERIR
INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES ("email@email.com","19999999999","123456789","Leo");

INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES ("guilherme.s.santos53@aluno.senai.br","19991951131","44627578822","Guilherme Staconi");

INSERT INTO CLIENTE (NOME,EMAIL,TELEFONE,CPF)
VALUES("Gabriel","gabriel@email.com","19994154099","22222222222");

-- SELECT - SELECIONAR
SELECT * FROM CLIENTE;

-- INSERIR PRODUTOS
INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("MacBook M4","Notebook Apple",4789.90,5);

SELECT * FROM PRODUTO;

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("iPhone 15 Pro Max","Smartphone top de linha",9999,15);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("iPhone 15", "Smartphone",7499,25);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("MacBook Air M2", "Notebook",8499,12);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUE ("MacBook Pro M3","Notebook",14999,8);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUE ("iPad Pro 12.9","Tablet",11999,10);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUE ("iPad 10ª Geração","Tablet com chip",3999,20);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUE ("Apple Watch Ultra 2","Smartwatch",6999,18);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUE ("Apple Watch Series 9","Smartwatch",4299,30);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUE ("AirPods Pro 2ª Geração","Fones de ouvido sem fio",2599,40);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUE ("AirTag (4 unidades)","Rastreador inteligente",1299,50);

-- INSERIR ALUGUEIS
SELECT * FROM CLIENTE;
SELECT * FROM PRODUTO;

INSERT INTO ALUGUEL (	DATA_ALUGUEL,
						DATA_DEVOLUCAO,
						VALOR_TOTAL,
						FK_CLIENTE_ID,
                        FK_PRODUTO_ID)
VALUES				(	"2025-09-24",
						"2025-10-01",
                        7890,
                        3,
                        2);

SELECT * FROM ALUGUEL;

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-01", "2025-09-08", 2500, 1, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-02", "2025-09-09", 1800, 2, 3);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-03", "2025-09-10", 3200, 3, 5);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-04", "2025-09-11", 1500, 4, 7);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-05", "2025-09-12", 999, 1, 3);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-06", "2025-09-13", 1200, 3, 10);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-07", "2025-09-14", 4500, 2, 2);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-08", "2025-09-15", 2700, 3, 4);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-09", "2025-09-16", 5500, 4, 6);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-10", "2025-09-17", 3100, 1, 8);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-11", "2025-09-18", 2999, 3, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-12", "2025-09-19", 3999, 2, 3);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-13", "2025-09-20", 4590, 2, 5);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-14", "2025-09-21", 2290, 3, 7);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-15", "2025-09-22", 890, 1, 9);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-16", "2025-09-23", 1350, 2, 10);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-17", "2025-09-24", 6250, 2, 2);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-18", "2025-09-25", 7200, 2, 4);

SELECT * FROM PRODUTO;

-- ATUALIZAR UM REGISTRO (UPDATE)
UPDATE 	PRODUTO
SET		PRECO = 3500
WHERE 	PRODUTO_ID = 1;

UPDATE 	PRODUTO
SET		PRECO = 3500
WHERE 	PRODUTO_ID = 9;

UPDATE 	PRODUTO
SET		PRECO = 2200
WHERE 	PRODUTO_ID = 3;

UPDATE 	PRODUTO
SET		PRECO = 9000
WHERE 	PRODUTO_ID = 5;

UPDATE 	PRODUTO
SET		QTD_DISPONIVEL = 200
WHERE 	PRODUTO_ID = 2;

UPDATE 	PRODUTO
SET		QTD_DISPONIVEL = 1000
WHERE 	PRODUTO_ID = 4;

UPDATE 	PRODUTO
SET		QTD_DISPONIVEL = 100
WHERE 	PRODUTO_ID = 5;

UPDATE 	PRODUTO
SET		QTD_DISPONIVEL = 70
WHERE 	PRODUTO_ID = 8;

UPDATE 	PRODUTO
SET		QTD_DISPONIVEL = 10
WHERE 	PRODUTO_ID = 9;

UPDATE 	CLIENTE
SET		EMAIL = "zacariasdagoiaba@email.com"
WHERE 	CLIENTE_ID = 2;

UPDATE 	CLIENTE
SET		EMAIL = "ryanclash@senai.com.br"
WHERE 	CLIENTE_ID = 3;

UPDATE 	ALUGUEL
SET		DATA_DEVOLUCAO = "2025-09-09"
WHERE 	ALUGUEL_ID = 1;

UPDATE 	ALUGUEL
SET		DATA_DEVOLUCAO = "2025-09-10"
WHERE 	ALUGUEL_ID = 2;

UPDATE 	ALUGUEL
SET		DATA_DEVOLUCAO = "2025-09-11"
WHERE 	ALUGUEL_ID = 3;

UPDATE 	ALUGUEL
SET		DATA_DEVOLUCAO = "2025-09-17"
WHERE 	ALUGUEL_ID = 4;

UPDATE 	ALUGUEL
SET		DATA_DEVOLUCAO = "2025-09-13"
WHERE 	ALUGUEL_ID = 5;

UPDATE 	ALUGUEL
SET		DATA_DEVOLUCAO = "2025-09-14"
WHERE 	ALUGUEL_ID = 6;

UPDATE 	ALUGUEL
SET		DATA_DEVOLUCAO = "2025-09-17"
WHERE 	ALUGUEL_ID = 7;

UPDATE 	ALUGUEL
SET		DATA_DEVOLUCAO = "2025-09-18"
WHERE 	ALUGUEL_ID = 8;

-- APAGAR UM REGISTRO (DELETE)
DELETE FROM CLIENTE WHERE CLIENTE_ID = 1;
DELETE FROM PRODUTO WHERE PRODUTO_ID = 4;
DELETE FROM ALUGUEL WHERE ALUGUEL_ID = 4;

SELECT * FROM CLIENTE;

SELECT 	*
FROM 	CLIENTE
WHERE 	CLIENTE_ID = 2;

SELECT 	NOME,S
		PRECO
FROM	PRODUTO
WHERE	PRODUTO_ID = 3;